# Generated by Django 4.2.7 on 2025-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='reviewed_by_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
