# Generated by Django 4.2.7 on 2025-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0002_exerciseplan_reviewed_by_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseplan',
            old_name='reviewed_by_fullname',
            new_name='reviewed_by_fullname_csspe',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='reviewed_by_fullname_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
