# Generated by Django 5.1.3 on 2024-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0002_alter_profile_activity_level_alter_profile_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='duration_per_day',
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='routine',
            field=models.JSONField(),
        ),
    ]
