# Generated by Django 5.1.3 on 2024-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0003_remove_exerciseplan_duration_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
    ]
