# Generated by Django 4.2.7 on 2025-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0003_rename_reviewed_by_fullname_exerciseplan_reviewed_by_fullname_csspe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='reviewed_by_fullname_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
