# Generated by Django 5.1.3 on 2024-12-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0004_remove_faculty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
    ]
