# Generated by Django 5.1.3 on 2024-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0005_profile_bmi'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['user', 'status'], name='seApp_dietp_user_id_2589e0_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseplan',
            index=models.Index(fields=['user', 'status'], name='seApp_exerc_user_id_289c68_idx'),
        ),
    ]
