# Generated by Django 4.2.7 on 2025-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0005_weightentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='fifth_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='first_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='fourth_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='second_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='sixth_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='third_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
