# Generated by Django 4.2.7 on 2025-08-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0006_exerciseplan_fifth_day_exerciseplan_first_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extremely_active', 'Extremely Active')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requires_equipment', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=20)),
                ('reps', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.activitylevel')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.exercisetype')),
            ],
            options={
                'unique_together': {('name', 'exercise_type', 'activity_level', 'requires_equipment')},
            },
        ),
    ]
