# Generated by Django 5.1.3 on 2024-12-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0006_dietplan_seapp_dietp_user_id_2589e0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_PlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('D_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.dietplan')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='E_PlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('E_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.exerciseplan')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.faculty')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanApproval',
        ),
    ]
