# Generated by Django 4.2.7 on 2025-08-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0007_activitylevel_exercisetype_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi_classification',
            field=models.TextField(default=0),
        ),
    ]
