# Generated by Django 4.2.7 on 2025-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0008_profile_bmi_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi_classification',
            field=models.TextField(),
        ),
    ]
