# Generated by Django 4.2.7 on 2025-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0009_alter_profile_bmi_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
