# Generated by Django 4.2.7 on 2025-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0010_alter_profile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weight_images/'),
        ),
    ]
