# Generated by Django 4.2.7 on 2025-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0011_weightentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
